### ISSUE TITLE
关于彩云小译

### ISSUE THREAD

**Issue by juzeon** [FeMiner/alfred-femine#1]
之前本人的项目一个功能也是调彩云小译网页翻译api的，前一段时间发现小译api突然加密了，由于本人不熟悉js所以代码审计了一个下午都搞不定target那又像base64又不是base64的加密方法。。。（jwt倒是很快就搞定了）

万幸偶然用github的code搜索拜读到了本项目，才发现原来还是base64+字母移位。感谢开发者。🙏

可以请开发者指点一下小译原app.js里面实现decode的这块代码的具体位置吗，非常想了解，不胜感谢！！🙏🙏

**Comment by FeMiner** [comment]
@juzeon 代码里搜索ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz

**Comment by juzeon** [comment]
已经找到了，感谢开发者回复！
